### PR TITLE
D8: Put Twig template cache directory outside the doc root

### PR DESCRIPTION
**Pull request by pjcdawkins**
Tested briefly on my own project

### CODE REVIEW

**Comment by Crell** [comment]
Are private files really the best place to put twig?  I'd expect them to be in a dedicated directory or in a disk cache directory or something.

**Comment by pjcdawkins** [comment]
It's confusing: Twig creates a sub-directory named `twig`, so the templates end up in `/app/private/twig`. That seems good to me.

Since it's a cache, I'd naturally put Twig templates in `tmp`, but that might not be appropriate for other "php_storage" files. So I decided that both the default php_storage and Twig should go in `private` (it doesn't seem to inherit from the default, which is super weird).

That said, I don't know what php_storage is supposed to be used for _apart_ from Twig... I can't think of a use case except maybe other template engines.

**Comment by Crell** [comment]
At one point it was also used for the compiled container, although that was changed late in the game to avoid issues with multi-head installations.  Although why Twig doesn't have the same issue I couldn't tell you.  (Probably something to do with the bootstrap, because bootstrap is always weird.)

Let's see if we can get someone from the core team in here to advise. I'm wary about using private files for something that should not be served, as private files are for access controlled servable files.  But we'll see.

**Comment by wimleers** [comment]
See https://www.drupal.org/node/2301163#comment-11275693. In short: this won't work as soon as you have >1 web server.

Issues to fix this:
- https://www.drupal.org/node/2301163
- https://www.drupal.org/node/2752961 (a more focused spin-off from the previous one)

Please help fix the latter!

**Comment by Crell** [comment]
Well, at the moment we don't support multi-head on Platform Standard anyway.  Multi-head would break with the default public files dir location for Twig anyway, wouldn't it?

**Comment by pjcdawkins** [comment]
@Crell this particular directory would be shared between the web instances (hence the `shared:files/private` in `.platform.app.yaml`). So that's not a problem even if/when we support multiple instances.

**Comment by Crell** [comment]
I discussed this with someone in the Drupal Contribute channel, and they couldn't see where it would cause an issue either.  So, let's go ahead and do it.

Thanks, @pjcdawkins and @wimleers!

**Pull request merged**
