### PR TITLE
Add drupal/console as php dependencies

### PR DESCRIPTION
**Pull request by mglaman**

### CODE REVIEW

**Comment by GuGuss** [comment]
@mglaman hi, any specific reason to have drupal/console in Platform.sh? Seems it's a read-only file system, there is not much you can do with the drupal/console IMHO.

**Comment by mglaman** [comment]
? Console isn't just for code generation. You can export/import databases, review watchdog logs, enable/disable modules. Debug routes (can't do in Drush), list goes on.

**Comment by GuGuss** [comment]
OK, I wasn't aware the console could do those things. I don't have a strong opinion against it then.

**Comment by pjcdawkins** [comment]
The risk here is if Console has dependencies that conflict with Drush... it seems OK for now... but Console and Drush are both encouraging Phar installs rather than Composer (which solves the global dependency issue)

**Pull request merged**
