### PR TITLE
Adding a working commerce composer-based Drupal 8 branch

### PR DESCRIPTION
**Pull request by joshmiller83**
Took me awhile to make a composer-based Drupal Commerce 2.x setup work for me. I'd love to hear the Platform team's thoughts on this "example" sample.

Note: I merged in bojan/mglamman's https://github.com/drupalcommerce/project-base repo with the 8.x-composer branch to get this working example. I have a feeling there are some extraneous pieces that could be removed.

### CODE REVIEW

**Comment by joshmiller83** [comment]
Note: I wanted this pull request to create a new branch ... for some reason it didn't. I'm not proposing overwriting the existing composer project.

**Comment by GuGuss** [comment]
👍

**Comment by joshmiller83** [comment]
Did some research and it seems I can't do a PR against a previously non-existant branch. So if you approve of this, then create a new branch called 8.x-composer-commerce2 based off the 8.x-composer branch. I'll then close this PR and create a new one against the new branch. 

Also, @GuGuss, I've got word we have a special Nirvana-drupal adult-medium-sized shirt being printed for you in the next few weeks. I should be able to pick it up when I'm in Kelowna in July.

:octocat: 

Josh

**Comment by GuGuss** [comment]
Just pushed `8.x-composer-commerce-2.x` branch.

**Pull request closed without merging**
