### PR TITLE
Provide a slightly better default hash_salt, with a warning if it's used

### PR DESCRIPTION
**Pull request by pjcdawkins**

### CODE REVIEW

**Comment by sruggier** [comment]
In an attempt to try to get rid of the need for a warning, I researched how this halt_salt thing is used. I ended up poking around [here](https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Site!Settings.php/function/calls/Settings%3A%3AgetHashSalt/8.2.x), and I get the impression that the value needs to be stable for a given site, or some transient stuff will get invalidated, similar to how truncating cache_form can invalidate forms. For example, [this call-site](https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Site!Settings.php/function/calls/Settings%3A%3AgetHashSalt/8.2.x) implies that changing it would invalidate all of the outstanding password reset emails for a given site. From that example, it also looks like it's implied that `hash_salt` should be secret for a given website, unlike salts in general, which are usually stored along with the thing they're being hashed, to thwart the use of rainbow tables.

So if this hash_salt value needs to be secret and also stable over time, I don't think we have any existing data to derive it from that meets those criteria. Could we generate a value randomly, and then persist it in a file under `/app/private`? I think that would be good enough to let us get rid of the warning and manual step.

**Comment by pjcdawkins** [comment]
That's all correct, and yes the solution is a good one and has been suggested before: we should generate a stable secret unique to each environment.

This PR is an interim measure which:

* doesn't damage the experience (it still sets a fallback hash_salt, so Drupal works with no config)
* avoids setting a hardcoded hash_salt to be the same for all projects
* warns when the fallback hash_salt is set, so the user knows to go and change it somewhere

**Comment by Crell** [comment]
I like the direction, but I'm wary about using trigger_error() as that's a very invasive message.  Unfortunately in order to put the message into Drupal's reports section we'd need to write a module, which is not something we can do just from the settings file. Hm. I will ponder a bit.

How do people feel about still releasing the composer version today, without this resolved?  (It's a pre-existing problem.)

**Comment by pjcdawkins** [comment]
It's less invasive than the D8 default, an uncaught exception, but yes it's not pretty... It looks like there might be some progress on providing this in the environment so I'll close this for now.

I'm fine for releasing #20 today, it's a big improvement.

**Pull request closed without merging**
